// ============================================================
// BUILDINGS DATA
// ============================================================
import { COLORS } from './constants.js';

export const BUILDINGS = {
  // ── BASIC PRODUCTION ──────────────────────────────────────
  mine: {
    id: 'mine', name: 'Mine', icon: '⛏', color: COLORS.ORE,
    cost: { gold: 50 },
    size: 1,
    category: 'production',
    tooltip: 'Produces Ore every 3s',
    production: { ore: 1 },
    productionRate: 3000,
    classes: null,
  },
  smelter: {
    id: 'smelter', name: 'Smelter', icon: '🔥', color: 0xff6030,
    cost: { gold: 80, ore: 5 },
    size: 1,
    category: 'production',
    tooltip: 'Converts Ore → Metal (2:1)',
    converts: { input: { ore: 2 }, output: { metal: 1 } },
    conversionRate: 4000,
    classes: null,
  },
  generator: {
    id: 'generator', name: 'Generator', icon: '⚡', color: COLORS.ENERGY,
    cost: { gold: 100, metal: 3 },
    size: 1,
    category: 'production',
    tooltip: 'Produces Energy every 2s',
    production: { energy: 1 },
    productionRate: 2000,
    classes: null,
  },
  crystalExtractor: {
    id: 'crystalExtractor', name: 'Crystal Extractor', icon: '💎', color: COLORS.CRYSTAL,
    cost: { gold: 150, energy: 5 },
    size: 1,
    category: 'production',
    tooltip: 'Produces Crystal every 5s',
    production: { crystal: 1 },
    productionRate: 5000,
    classes: null,
  },
  essenceCollector: {
    id: 'essenceCollector', name: 'Essence Collector', icon: '✨', color: COLORS.ESSENCE,
    cost: { gold: 200, crystal: 3 },
    size: 1,
    category: 'production',
    tooltip: 'Produces Essence every 8s. Essence powers meta upgrades.',
    production: { essence: 1 },
    productionRate: 8000,
    classes: null,
  },

  // ── COMBAT BUILDINGS ──────────────────────────────────────
  turret: {
    id: 'turret', name: 'Turret', icon: '🗼', color: 0x8080ff,
    cost: { gold: 120, metal: 5 },
    size: 1,
    category: 'combat',
    tooltip: 'Fires at enemies. Range 3. Damage 15.',
    damage: 15, range: 3, fireRate: 1200,
    classes: null,
  },
  cannon: {
    id: 'cannon', name: 'Cannon', icon: '💣', color: 0xd06040,
    cost: { gold: 200, metal: 10, energy: 3 },
    size: 1,
    category: 'combat',
    tooltip: 'Slow but devastating AoE. Range 4. Damage 60.',
    damage: 60, range: 4, fireRate: 3000, aoe: 1.5,
    classes: null,
  },
  laserTower: {
    id: 'laserTower', name: 'Laser Tower', icon: '🔆', color: 0xff3060,
    cost: { gold: 250, energy: 15, crystal: 3 },
    size: 1,
    category: 'combat',
    tooltip: 'Continuous beam. Burns through shields. Range 5. DPS 20.',
    damage: 5, range: 5, fireRate: 250, piercing: true,
    classes: null,
  },
  wallSegment: {
    id: 'wallSegment', name: 'Wall', icon: '🧱', color: 0x706050,
    cost: { gold: 30, ore: 3 },
    size: 1,
    category: 'defense',
    tooltip: 'Blocks enemy path. HP 200.',
    hp: 200, isWall: true,
    classes: null,
  },
  shieldGenerator: {
    id: 'shieldGenerator', name: 'Shield Gen', icon: '🛡', color: 0x40a0ff,
    cost: { gold: 180, energy: 8 },
    size: 1,
    category: 'defense',
    tooltip: 'Projects a shield reducing damage by 40% in range 2.',
    shieldRange: 2, shieldReduction: 0.4,
    classes: null,
  },

  // ── LOGISTICS ─────────────────────────────────────────────
  conveyor: {
    id: 'conveyor', name: 'Conveyor', icon: '➡', color: 0x606060,
    cost: { gold: 20, metal: 1 },
    size: 1,
    category: 'logistics',
    tooltip: 'Moves resources between buildings. +25% throughput.',
    throughputBonus: 0.25,
    classes: null,
  },
  storehouse: {
    id: 'storehouse', name: 'Storehouse', icon: '🏪', color: 0x806040,
    cost: { gold: 80 },
    size: 1,
    category: 'logistics',
    tooltip: 'Doubles max storage capacity.',
    storageMultiplier: 2,
    classes: null,
  },
  market: {
    id: 'market', name: 'Market', icon: '💹', color: 0xf0a030,
    cost: { gold: 150, metal: 5 },
    size: 1,
    category: 'logistics',
    tooltip: 'Converts any resource to Gold at 80% value every 5s.',
    conversionRate: 5000, goldRate: 0.8,
    classes: null,
  },

  // ── CLASS-SPECIFIC: ENGINEER ──────────────────────────────
  overdrivePylon: {
    id: 'overdrivePylon', name: 'Overdrive Pylon', icon: '⚙', color: COLORS.ENGINEER,
    cost: { gold: 180, metal: 8, energy: 5 },
    size: 1,
    category: 'special',
    tooltip: '[Engineer] Nearby buildings produce 50% faster.',
    aura: { productionSpeed: 1.5, range: 2 },
    classes: ['engineer'],
  },
  assembler: {
    id: 'assembler', name: 'Assembler', icon: '🤖', color: COLORS.ENGINEER,
    cost: { gold: 220, metal: 15 },
    size: 1,
    category: 'special',
    tooltip: '[Engineer] Auto-builds cheap buildings from stockpile.',
    classes: ['engineer'],
    special: 'assembler',
  },
  overclocker: {
    id: 'overclocker', name: 'Overclocker', icon: '🔩', color: COLORS.ENGINEER,
    cost: { gold: 200, metal: 10, energy: 10 },
    size: 1,
    category: 'special',
    tooltip: '[Engineer] Doubles one adjacent turret\'s fire rate.',
    classes: ['engineer'],
    special: 'overclocker',
  },

  // ── CLASS-SPECIFIC: ALCHEMIST ─────────────────────────────
  transmutationCircle: {
    id: 'transmutationCircle', name: 'Transmutation Circle', icon: '🔮', color: COLORS.ALCHEMIST,
    cost: { gold: 160, crystal: 5 },
    size: 1,
    category: 'special',
    tooltip: '[Alchemist] Converts any resource into any other (1:1 efficiency).',
    classes: ['alchemist'],
    special: 'transmutationCircle',
  },
  poisonVat: {
    id: 'poisonVat', name: 'Poison Vat', icon: '🧪', color: COLORS.ALCHEMIST,
    cost: { gold: 140, essence: 3 },
    size: 1,
    category: 'special',
    tooltip: '[Alchemist] Poisons enemies in range 2. -5 HP/s.',
    damage: 5, range: 2, tickRate: 1000, dot: true,
    classes: ['alchemist'],
  },
  potionBrewery: {
    id: 'potionBrewery', name: 'Potion Brewery', icon: '⚗', color: COLORS.ALCHEMIST,
    cost: { gold: 190, crystal: 8, essence: 2 },
    size: 1,
    category: 'special',
    tooltip: '[Alchemist] Brews random potions that buff nearby buildings.',
    classes: ['alchemist'],
    special: 'potionBrewery',
  },

  // ── CLASS-SPECIFIC: WARLORD ──────────────────────────────
  barracks: {
    id: 'barracks', name: 'Barracks', icon: '⚔', color: COLORS.WARLORD,
    cost: { gold: 200, metal: 10 },
    size: 1,
    category: 'special',
    tooltip: '[Warlord] Spawns soldier units that fight enemies.',
    classes: ['warlord'],
    special: 'barracks',
    spawnRate: 10000, soldierHP: 60, soldierDmg: 10,
  },
  warForge: {
    id: 'warForge', name: 'War Forge', icon: '🗡', color: COLORS.WARLORD,
    cost: { gold: 240, metal: 15, ore: 10 },
    size: 1,
    category: 'special',
    tooltip: '[Warlord] Upgrades all soldiers: +50% damage and HP.',
    classes: ['warlord'],
    special: 'warForge',
  },
  siegeCatapult: {
    id: 'siegeCatapult', name: 'Siege Catapult', icon: '🏹', color: COLORS.WARLORD,
    cost: { gold: 280, metal: 20 },
    size: 1,
    category: 'special',
    tooltip: '[Warlord] Massive range (7), slow fire, huge AoE damage (120).',
    damage: 120, range: 7, fireRate: 5000, aoe: 2.5,
    classes: ['warlord'],
  },

  // ── CLASS-SPECIFIC: NATURALIST ───────────────────────────
  growthSpire: {
    id: 'growthSpire', name: 'Growth Spire', icon: '🌿', color: COLORS.NATURALIST,
    cost: { gold: 130, essence: 5 },
    size: 1,
    category: 'special',
    tooltip: '[Naturalist] Boosts adjacent production buildings +1 resource/tick.',
    classes: ['naturalist'],
    aura: { productionBonus: 1, range: 1 },
  },
  thornwall: {
    id: 'thornwall', name: 'Thornwall', icon: '🌵', color: COLORS.NATURALIST,
    cost: { gold: 90, essence: 3 },
    size: 1,
    category: 'special',
    tooltip: '[Naturalist] Wall that reflects 20 damage when hit.',
    hp: 150, isWall: true, reflect: 20,
    classes: ['naturalist'],
  },
  symbioteHive: {
    id: 'symbioteHive', name: 'Symbiote Hive', icon: '🍄', color: COLORS.NATURALIST,
    cost: { gold: 170, essence: 8, crystal: 3 },
    size: 1,
    category: 'special',
    tooltip: '[Naturalist] Spawns flying symbiotes that slow and damage enemies.',
    classes: ['naturalist'],
    special: 'symbioteHive',
  },

  // ── CLASS-SPECIFIC: CHRONOMANCER ─────────────────────────
  timeAnchor: {
    id: 'timeAnchor', name: 'Time Anchor', icon: '⏳', color: COLORS.CHRONOMANCER,
    cost: { gold: 210, crystal: 10 },
    size: 1,
    category: 'special',
    tooltip: '[Chronomancer] Slows all enemies in range 3 by 50%.',
    classes: ['chronomancer'],
    slow: 0.5, range: 3,
  },
  loopChamber: {
    id: 'loopChamber', name: 'Loop Chamber', icon: '🔄', color: COLORS.CHRONOMANCER,
    cost: { gold: 250, crystal: 12, energy: 8 },
    size: 1,
    category: 'special',
    tooltip: '[Chronomancer] Buildings in range 2 trigger twice per tick.',
    classes: ['chronomancer'],
    aura: { doubleProduction: true, range: 2 },
  },
  temporalMine: {
    id: 'temporalMine', name: 'Temporal Mine', icon: '💥', color: COLORS.CHRONOMANCER,
    cost: { gold: 160, crystal: 6 },
    size: 1,
    category: 'special',
    tooltip: '[Chronomancer] Triggers a time explosion when enemy steps near. Stuns + 80dmg.',
    classes: ['chronomancer'],
    special: 'temporalMine', damage: 80, stunDuration: 3000,
  },
};

export const BUILDING_CATEGORIES = {
  production: 'Production',
  combat: 'Combat',
  defense: 'Defense',
  logistics: 'Logistics',
  special: 'Class Special',
};
